// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc.Data;

#nullable disable

namespace QuanLyKhoaHoc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507063710_ThemThanhToan")]
    partial class ThemThanhToan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc.Models.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHienThi")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanLienKet")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.BuoiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDienRa")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<int?>("LichHocId")
                        .HasColumnType("int");

                    b.Property<string>("LinkMeet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoBuoiThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("LichHocId");

                    b.ToTable("BuoiHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTienDaThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("HocVienId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int>("DangKyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiemChuyenCan")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemTrungBinh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("DuDieuKienCapChungChi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("XepLoai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyId")
                        .IsUnique();

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DiemDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuoiHocId")
                        .HasColumnType("int");

                    b.Property<int>("DangKyId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("NgayDiemDanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DangKyId");

                    b.HasIndex("BuoiHocId", "DangKyId")
                        .IsUnique();

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BangCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("GioiThieu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaGiangVien")
                        .IsUnique();

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHocVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TrinhDoHienTai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaHocVien")
                        .IsUnique();

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThoiLuongMoiBuoi")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaKhoaHoc")
                        .IsUnique();

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LichHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("LinkMeetMacDinh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("LichHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.PhanCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("GiangVienId", "KhoaHocId")
                        .IsUnique();

                    b.ToTable("PhanCongs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.BaiViet", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.BuoiHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachBuoiHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc.Models.LichHoc", "LichHoc")
                        .WithMany("DanhSachBuoiHoc")
                        .HasForeignKey("LichHocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhoaHoc");

                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DangKy", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.HocVien", "HocVien")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.Diem", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.DangKy", "DangKy")
                        .WithOne("Diem")
                        .HasForeignKey("QuanLyKhoaHoc.Models.Diem", "DangKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKy");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DiemDanh", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.BuoiHoc", "BuoiHoc")
                        .WithMany("DanhSachDiemDanh")
                        .HasForeignKey("BuoiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc.Models.DangKy", "DangKy")
                        .WithMany()
                        .HasForeignKey("DangKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuoiHoc");

                    b.Navigation("DangKy");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.GiangVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.NguoiDung", "NguoiDung")
                        .WithOne("GiangVien")
                        .HasForeignKey("QuanLyKhoaHoc.Models.GiangVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HocVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.NguoiDung", "NguoiDung")
                        .WithOne("HocVien")
                        .HasForeignKey("QuanLyKhoaHoc.Models.HocVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LichHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachLichHoc")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.PhanCong", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachPhanCong")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyKhoaHoc.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachPhanCong")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.BuoiHoc", b =>
                {
                    b.Navigation("DanhSachDiemDanh");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.DangKy", b =>
                {
                    b.Navigation("Diem");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.GiangVien", b =>
                {
                    b.Navigation("DanhSachPhanCong");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.HocVien", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KhoaHoc", b =>
                {
                    b.Navigation("DanhSachBuoiHoc");

                    b.Navigation("DanhSachDangKy");

                    b.Navigation("DanhSachLichHoc");

                    b.Navigation("DanhSachPhanCong");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.LichHoc", b =>
                {
                    b.Navigation("DanhSachBuoiHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.NguoiDung", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
